document_type: "Cameroon_NIC_v2"
backgrounds:
  - "data/bg/cameroon_nic_v2/front_blank.png"
  - "data/bg/cameroon_nic_v2/back_blank.png"
fonts: "data/fonts/"
json_dir: "data/json/nic_v2"
fields:
  # --- FRONT ---
  - name: "surname"
    position: [392, 223]
    font: "Roboto-VariableFont_wdth,wght.ttf"
    stroke_width: 0.3
    size: 20
    side: "front"
  - name: "given_names"
    position: [392, 302]
    font: "Roboto-VariableFont_wdth,wght.ttf"
    stroke_width: 0.3
    size: 20
    side: "front"
  - name: "date_of_birth"
    position: [392, 378]
    font: "Roboto-VariableFont_wdth,wght.ttf"
    stroke_width: 0.3
    size: 20
    side: "front"
  - name: "place_of_birth"
    position: [392, 423]
    font: "Roboto-VariableFont_wdth,wght.ttf"
    stroke_width: 0.3
    size: 20
    side: "front"
  - name: "sex"
    position: [392, 470]
    font: "Roboto-VariableFont_wdth,wght.ttf"
    stroke_width: 0.3
    size: 20
    side: "front"
  - name: "height"
    position: [498, 470]
    font: "Roboto-VariableFont_wdth,wght.ttf"
    stroke_width: 0.3
    size: 20
    side: "front"
  - name: "occupation"
    position: [392, 516]
    font: "Roboto-VariableFont_wdth,wght.ttf"
    stroke_width: 0.3
    size: 20
    side: "front"

    # --- BACK ---
  - name: "father_name"
    position: [137, 170]
    font: "Roboto-VariableFont_wdth,wght.ttf"
    stroke_width: 0.3
    size: 20
    side: "back"
  - name: "mother_name"
    position: [137, 242]
    font: "Roboto-VariableFont_wdth,wght.ttf"
    stroke_width: 0.3
    size: 20
    side: "back"
  - name: "proffessional_matrimonial_situatn"
    position: [137, 318]
    font: "Roboto-VariableFont_wdth,wght.ttf"
    stroke_width: 0.3
    size: 20
    side: "back"
  - name: "address"
    position: [137, 380]
    font: "Roboto-VariableFont_wdth,wght.ttf"
    stroke_width: 0.3
    size: 20
    side: "back"
  - name: "issue_date"
    position: [574, 338]
    font: "Roboto-VariableFont_wdth,wght.ttf"
    stroke_width: 0.3
    size: 20
    side: "back"
  - name: "expiry_date"
    position: [574, 406]
    font: "Roboto-VariableFont_wdth,wght.ttf"
    stroke_width: 0.3
    size: 20
    side: "back"
  - name: "post_id"
    position: [738, 336]
    font: "Roboto-VariableFont_wdth,wght.ttf"
    stroke_width: 0.3
    size: 20
    side: "back"
  - name: "unique_id"
    position: [737, 406]
    font: "Roboto-VariableFont_wdth,wght.ttf"
    stroke_width: 0.3
    size: 20
    side: "back"